version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-cli-version: latest
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: awsContext
          create-repo: true
          dockerfile: Dockerfile
          public-registry: false
          push-image: true
          region: 'us-west-1'
          registry-id: AWS_ECR_REGISTRY_ID
          repo: aws-test
          repo-scan-on-push: true
          role-arn: 'arn:aws:iam::669382012465:role/docker-training-ReadWrite'
          skip-when-tags-exist: false
          security-token: SECURITY_TOKEN_ENV_VAR_NAME

