version: 2.1
orbs:
  awscli: appfolio/awscli@1.0.0
jobs:
  awscli-example:
    executor: awscli/default
    steps:
      - checkout
      - awscli/setup:
          profile-name: my-aws
          aws-access-key-id: ${ACCESS_KEY_ID_ENV_VAR_NAME}
          aws-secret-access-key: ${SECRET_ACCESS_KEY_ENV_VAR_NAME}
          aws-region: 'us-west-1'
          assume-role: ${AWS_ASSUME_ROLE}
          role-arn: ${AWS_ROLE_ARN}
      - run: echo "set up successfully"
workflows:
  version: 2
  awscli:
    jobs:
      - awscli-example:
          context: awsContext
