version: 2.1

jobs:
  Login-in-Aws:
    description: login in aws
    parameters:
      profile-name: myAWS
      aws-access-key-id: AWS_ACCESS_KEY_ID
      aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      aws-region: 'us-west-1'
      assume-role: true
      role-arn: AWS_ROLE_ARN
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - Login-in-Aws

