version: 2.1

jobs:
  Login-in-Aws:
    description: login in aws
    parameters:
      profile-name: myAWS
      aws-access-key-id: AWS_ACCESS_KEY_ID
      aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      aws-region: 'us-west-1'
      assume-role: true
      role-arn: AWS_ROLE_ARN
    steps:
      - run:
          name: Configure AWS credentials
          command: >
            aws configure set aws_access_key_id $<<parameters.aws-access-key-id>> \
            --profile <<parameters.profile-name>>
            aws configure set aws_secret_access_key
            $<<parameters.aws-secret-access-key>> \
            --profile <<parameters.profile-name>>
            - run:
                name: Configure AWS default region
                command: |
                  aws configure set region $<<parameters.aws-region>> \
                    --profile <<parameters.profile-name>>
            - when:
                condition: <<parameters.assume-role>>
                steps:
                  - run:
                      name: Configure AWS IAM role to assume
                      command: |
                        aws configure set role_arn $<<parameters.role-arn>> \
                          --profile <<parameters.profile-name>>
                        aws configure set source_profile <<parameters.profile-name>> \
                          --profile <<parameters.profile-name>>
workflows:
  version: 2
  awscli:
    jobs:
      - Login-in-Aws:
        context: aws

