version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: ':docker: Build and package image'
          agents:
            queue: rea-artifacts:build

workflows:
  build_and_upload:
    jobs:
      - say-hello
