version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: ':docker: Build and package image'
          agents:
            queue: rea-artifacts:build
          plugins:
            - ssh://git@git.realestate.com.au/buildkite-plugin/ecr-release-buildkite-plugin#v1:
                namespace: aws-test
                repository: aws-test
                tags:
                  - "aws-test-ke"
                tag-latest: true

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
